extends Object
class_name fTxt

static var victorytitle = "Boss Purged"
static var victorySubtitles = [
	"good job",
	"incredible victory",
	"memory reallocated",
	"hunt complete",
	"grand success",
	"beautiful triumph",
	"well done",
	"congratulations",
	"you cooked",
	"mom get the camera",
	"astronomic victory",
	"stellar achievement",
	"aight you win",
	"balance restored",
	"the king is dead",
	"harmony blossoms",
	"holy moly",
	"one for the books",
	"a star is born",
]

static var defeattitle = "You are Dead"
static var defeatSubtitles = [
	"all hope is lost",
	"you had one job",
	"millions silenced",
	"the gods weep",
	"how unfortunate",
	"tragedy strikes",
	"don't give up",
	"a slight setback",
	"another hero lost",
	"not again",
	"destiny obstructed",
	"the darkest hour",
	"rest in peace",
	"the stars collide",
	"it's so joever",
	"olympus has fallen",
	"objective failed",
	"maybe next time",
	"oof",
	"unlucky",
	"that's gotta hurt"
]

static var playerNames = [
	"clb",
	"hrt",
	"dia",
	"spd",
	"str",
	"mon",
	"crn",
	"syn",
	"sym",
	"arc",
	"yue",
	"jam",
	"tae",
	"yae",
	"bob",
	"qwn",
	"foe",
	"red",
	"blu",
	"opp",
	"xei",
	"zho",
	"rem",
	"ram",
	"sue",
	"law",
	"iou",
	"woe",
	"qte",
	"xor",
	"nor",
	"and",
	"cho",
	"zoe",
	"nme",
	"wes",
	"why",
	"wax",
	"frt",
	"fsh",
	"brj",
	"rsh",
	"dyn",
	"lax",
	"swg",
	"sha",
	"art",
	"cfe",
	"jva",
	"ply",
	"rym",
	"cos",
	"tan",
	"sin",
	"rok",
	"lee",
	"mal",
	"wre",
	"lud",
	"bud",
	"rar",
	"vlc",
	"qol",
	"num",
	"del",
	"alt",
	"css",
	"sfx",
	"vfx",
	"gfx",
	"gdt",
	"cap",
	"lit",
	"var",
	"int",
	"inf",
	"def"
]

static var tips = [
	"Some jobs let you click on players to perform a support skill.",
	"Some Barrels contain weapons, click to loot them.",
	"Stay out of the red!",
	"Wells contain surprises, try clicking on one.",
	"Some weapons can heal you as you attack!",
	"Some weapons can prevent damage or even, deal it back!?",
	"Weapon damage is a cummulation of dice rolls!",
	"Watch out for dashes and charges! They can stun you!",
]
